Repository 9oormthon-univ/2025_SEASONTHON_TEAM_60_BE, pull requests merged in 2025-09, with the labels that each got.

#8 [INIT/#5] Initializer 구축
  src/main/java/com/veribadge/veribadge/domain/Badge.java
  src/main/java/com/veribadge/veribadge/domain/Member.java
  src/main/java/com/veribadge/veribadge/domain/Verification.java
  src/main/java/com/veribadge/veribadge/global/status/ErrorStatus.java
  src/main/java/com/veribadge/veribadge/mock/BadgeInitializer.java
  src/main/java/com/veribadge/veribadge/mock/MemberInitializer.java
  src/main/java/com/veribadge/veribadge/mock/VerificationInitializer.java
  src/main/java/com/veribadge/veribadge/repository/BadgeRepository.java
  src/main/java/com/veribadge/veribadge/repository/MemberRepository.java
  src/main/java/com/veribadge/veribadge/repository/VerificationRepository.java
  src/main/resources/application.yml
Labels: init

#9 [Feat/#5] swagger 설정 및 대시보드, 나의 뱃지 관리 페이지 get 구현
  build.gradle
  src/main/java/com/veribadge/veribadge/config/SwaggerConfig.java
  src/main/java/com/veribadge/veribadge/controller/MainController.java
  src/main/java/com/veribadge/veribadge/controller/MyBadgeController.java
  src/main/java/com/veribadge/veribadge/dto/DashboardResponseDto.java
  src/main/java/com/veribadge/veribadge/dto/MyBadgeResponseDto.java
  src/main/java/com/veribadge/veribadge/global/status/SuccessStatus.java
  src/main/java/com/veribadge/veribadge/repository/MemberRepository.java
  src/main/java/com/veribadge/veribadge/service/MainService.java
  src/main/java/com/veribadge/veribadge/service/MyBadgeService.java
Labels: ✨ feature, init

#12 [FEAT] 뱃지 검증 및 매칭 기능
  build.gradle
  src/main/java/com/veribadge/veribadge/SecurityConfig.java
  src/main/java/com/veribadge/veribadge/WebConfig.java
  src/main/java/com/veribadge/veribadge/controller/BadgeController.java
  src/main/java/com/veribadge/veribadge/domain/Badge.java
  src/main/java/com/veribadge/veribadge/domain/Member.java
  src/main/java/com/veribadge/veribadge/dto/BadgeVerifyResponseDto.java
  src/main/java/com/veribadge/veribadge/dto/CommentTagVerifyRequestDto.java
  src/main/java/com/veribadge/veribadge/global/status/SuccessStatus.java
  src/main/java/com/veribadge/veribadge/repository/BadgeRepository.java
  src/main/java/com/veribadge/veribadge/service/BadgeMatcherService.java
  src/main/java/com/veribadge/veribadge/veribadge_frontend/background.js
  src/main/java/com/veribadge/veribadge/veribadge_frontend/contentScript.js
  src/main/java/com/veribadge/veribadge/veribadge_frontend/icons/icon.png
  src/main/java/com/veribadge/veribadge/veribadge_frontend/images/diamond.png
  src/main/java/com/veribadge/veribadge/veribadge_frontend/images/gold.png
  src/main/java/com/veribadge/veribadge/veribadge_frontend/images/platinum.png
  src/main/java/com/veribadge/veribadge/veribadge_frontend/images/silver.png
  src/main/java/com/veribadge/veribadge/veribadge_frontend/injectBadge.js
  src/main/java/com/veribadge/veribadge/veribadge_frontend/manifest.json
  src/main/java/com/veribadge/veribadge/veribadge_frontend/popup/popup.html
Labels: ✨ feature

#19 [Feat/#13]구글 연결해서 유튜브 링크, 이메일 저장 + 고유 태그 발급
  build.gradle
  src/main/java/com/veribadge/veribadge/config/SecurityConfig.java
  src/main/java/com/veribadge/veribadge/controller/AuthController.java
  src/main/java/com/veribadge/veribadge/controller/MemberController.java
  src/main/java/com/veribadge/veribadge/controller/MyBadgeController.java
  src/main/java/com/veribadge/veribadge/domain/Badge.java
  src/main/java/com/veribadge/veribadge/domain/Member.java
  src/main/java/com/veribadge/veribadge/global/status/ErrorStatus.java
  src/main/java/com/veribadge/veribadge/google/CustomOAuth2SuccessHandler.java
  src/main/java/com/veribadge/veribadge/google/GoogleController.java
  src/main/java/com/veribadge/veribadge/google/GoogleService.java
  src/main/java/com/veribadge/veribadge/jwt/JwtAuthenticationFilter.java
  src/main/java/com/veribadge/veribadge/jwt/JwtProvider.java
  src/main/java/com/veribadge/veribadge/service/MemberService.java
  src/main/java/com/veribadge/veribadge/service/MyBadgeService.java
Labels: ✨ feature

#24 [Chore/#18] create get current user
  src/main/java/com/veribadge/veribadge/config/SecurityConfig.java
  src/main/java/com/veribadge/veribadge/controller/AuthController.java
  src/main/java/com/veribadge/veribadge/controller/MainController.java
  src/main/java/com/veribadge/veribadge/controller/MyBadgeController.java
  src/main/java/com/veribadge/veribadge/domain/Member.java
  src/main/java/com/veribadge/veribadge/global/status/ErrorStatus.java
  src/main/java/com/veribadge/veribadge/google/GoogleController.java
  src/main/java/com/veribadge/veribadge/handler/CustomOAuth2SuccessHandler.java
  src/main/java/com/veribadge/veribadge/repository/MemberRepository.java
  src/main/java/com/veribadge/veribadge/service/AuthService.java
  src/main/java/com/veribadge/veribadge/service/MainService.java
  src/main/java/com/veribadge/veribadge/service/MyBadgeService.java
  src/main/java/com/veribadge/veribadge/service/social/GoogleService.java
  src/main/java/com/veribadge/veribadge/service/social/KakaoService.java
  src/main/resources/application.yml
Labels: ✨ feature
